import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Roboto } from "next/font/google";
import Header from "./(component)/head/header";

const square = localFont({
    src: "./fonts/NanumSquareNeo/NanumSquareNeo-Variable.woff2",
    variable: "--font-square",
    weight: "100 900",
});

export const roboto = Roboto({
    subsets: ["latin"],
    weight: ["300", "400", "700"],
    variable: "--font-roboto", // Tailwind에서 변수로 사용하려면
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${square.variable} ${roboto.variable} antialiased p-10`}
            >
                <header className="text-[24px] font-square">
                    <Header />
                </header>
                {children}
            </body>
        </html>
    );
}
